### PR TITLE
added popup

### PR DESCRIPTION
**Pull request by kvssankar**
Bhaiya check it and tell me what changes are to be done @ArpitKotecha

### CODE REVIEW

**Comment by ArpitKotecha** [comment]
Also, add a field to enter github id

**Comment by kvssankar** [comment]
Added git hub field
Before checkboxes were not working fixed them
Made some JS changes

**Comment by ArpitKotecha** [comment]
@kvssankar 

- [ ] Remove Live Updates Button and place register button there.
- [ ] Give some border or change a color/contrast of register button so it can be little more visible.
- [ ] Also change border of the input elements to blue(the one used in icon bg circle) from pink

**Comment by kvssankar** [comment]
Done all changes u have said bhaiya
Also changed the pop up background

**Pull request closed without merging**
